# frozen_string_literal: true

source 'https://rubygems.org'

gem 'httparty'
gem 'pry'
gem 'rb-readline'
gem 'redis'
gem 'rest-client'

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'ruby-prof'
  gem 'solargraph'
end
