default: &default
  window_manager:
    mac_renderer: <%= ENV['EXTEND_WM_MAC_RENDERER'] || 'Hammerspoon' %>
    windows_renderer: <%= ENV['EXTEND_WM_WINDOWS_RENDERER'] || 'Autohotkey' %>
    linux_renderer: <%= ENV['EXTEND_WM_MAC_RENDERER'] || 'Sxhkd' %>
    modifier: <%= ENV['EXTEND_WM_MODIFIER'] || 'alt' %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
